import sys

f = r"C:\Users\ASUS ZenBook\plateforme-immobiliere\frontend\real_estate_front\src\pages\CartePage.jsx"
with open(f, 'r', encoding='utf-8') as fh:
    c = fh.read()

r = '�'

fixes = [
    # Price eval bar labels
    ('Aucune ' + r + 'valuation', 'Aucune évaluation'),
    ('Prix tr' + r + 's ' + r + 'lev' + r, 'Prix très élevé'),
    ('Prix ' + r + 'lev' + r, 'Prix élevé'),
    ('Prix ' + r + 'quitable', 'Prix équitable'),
    ('Tr' + r + 's bon prix', 'Très bon prix'),
    ('Bon march' + r, 'Bon marché'),
    # POI filter buttons
    (r + 'coles', 'Écoles'),
    ('Mosqu' + r + 'es', 'Mosquées'),
    ('Mosqu' + r + 'e', 'Mosquée'),
    ('Facult' + r + 's', 'Facultés'),
    # Type bien
    ('D' + r + 'p' + r + 't de stockage', 'Dépôt de stockage'),
    # Etat labels
    ('Bon ' + r + 'tat', 'Bon état'),
    (r + ' r' + r + 'nover', 'à rénover'),
    # Filter labels
    ('Pi' + r + 'ces min', 'Pièces min'),
    (r + 'tat du bien', 'État du bien'),
    ('R' + r + 'sidentielle', 'Résidentielle'),
    (r + 'conomique', 'Économique'),
    ('Autres crit' + r + 'res', 'Autres critères'),
    ('Caract' + r + 'ristiques', 'Caractéristiques'),
    ('S' + r + 'lectionnez les ' + r + 'quipements souhait' + r + 's', 'Sélectionnez les équipements souhaités'),
    ('Meubl' + r, 'Meublé'),
    ('Chemin' + r + 'e', 'Cheminée'),
    ('blind' + r + 'e', 'blindée'),
    ('S' + r + 'curit' + r, 'Sécurité'),
    ('Machine ' + r + ' laver', 'Machine à laver'),
    ('Cuisine ' + r + 'quip' + r + 'e', 'Cuisine équipée'),
    ('Vue sur for' + r + 't', 'Vue sur forêt'),
    ('Espaces ext' + r + 'rieurs', 'Espaces extérieurs'),
    ('Commodit' + r + 's', 'Commodités'),
    ('Int' + r + 'rieur & ' + r + 'quipements', 'Intérieur & équipements'),
    ('Int' + r + 'rieur', 'Intérieur'),
    (r + 'quipements', 'équipements'),
    (r + 'quipement', 'équipement'),
    (r + 'quip' + r + 'e', 'équipée'),
    ('anciennet' + r, 'ancienneté'),
    ('Anciennet' + r, 'Ancienneté'),
    ('standing', 'standing'),
    # Hover card
    (r + 'valuation', 'évaluation'),
    ('toujours affich' + r + 'e', 'toujours affichée'),
    # Map hover
    (r + ' {hoveredPin.gouvernorat}', ' · {hoveredPin.gouvernorat}'),
    ('{hoveredPin.delegation} ' + r, '{hoveredPin.delegation} ·'),
    ('{p.delegation} ' + r, '{p.delegation} ·'),
    # Pagination
    ('trouv' + r + 'es', 'trouvées'),
    ('trouv' + r + 'e', 'trouvée'),
    ('trouv' + r, 'trouvé'),
    ('D' + r + 'zoomez', 'Dézoomez'),
    # Comparison popup
    ('s' + r + 'lectionn' + r + 's', 'sélectionnés'),
    ('s' + r + 'lectionn' + r + 'e', 'sélectionnée'),
    ('s' + r + 'lectionn' + r, 'sélectionné'),
    ('S' + r + 'lectionnez des biens', 'Sélectionnez des biens'),
    ('s' + r + 'lectionner au moins', 'sélectionner au moins'),
    # Static school/mosque/faculty names in data arrays
    ('Coll' + r + 'ge', 'Collège'),
    ('Lyc' + r + 'e', 'Lycée'),
    ('M' + r + 'denine', 'Médenine'),
    ('M' + r + 'dina', 'Médina'),
    ('G' + r + 'ant', 'Géant'),
    (r + 'cole', 'École'),
    ('Universit' + r, 'Université'),
    ('Facult' + r + ' de M' + r + 'decine', 'Faculté de Médecine'),
    ('Facult' + r + ' des Sciences', 'Faculté des Sciences'),
    ('Facult' + r + ' Droit', 'Faculté Droit'),
    ('Facult' + r, 'Faculté'),
    # Terrain/location types
    ('R' + r + 'sidence ferm' + r + 'e', 'Résidence fermée'),
    # Comments cleanup
    (r + 'VALUATION DU PRIX', 'ÉVALUATION DU PRIX'),
    ('color' + r + 's', 'colorés'),
    ('priorit' + r + ' absolue', 'priorité absolue'),
    ('moiti' + r, 'moitié'),
    ('fra' + r + 'cheur', 'fraîcheur'),
    ('al' + r + 'atoirement', 'aléatoirement'),
    ('d' + r + 'partag' + r + 's', 'départagés'),
    ('qualit' + r, 'qualité'),
    # Generic common patterns
    ('nuit' + r + 'e', 'nuitée'),
    ('ann' + r + 'e', 'année'),
    ('ann' + r + 'es', 'années'),
    ('Valid' + r, 'Validé'),
    ('tr' + r + 's', 'très'),
    ('Tr' + r + 's', 'Très'),
    ('m' + r + 'me', 'même'),
    ('M' + r + 'me', 'Même'),
    ('r' + r + 'el', 'réel'),
    ('r' + r + 'gle', 'règle'),
    ('r' + r + 'gl', 'régl'),
    ('mod' + r + 'le', 'modèle'),
    ('donn' + r + 'es', 'données'),
    ('donn' + r + 'e', 'donnée'),
    ('acc' + r + 's', 'accès'),
    ('Acc' + r + 's', 'Accès'),
    ('d' + r + 'clenche', 'déclenche'),
    ('D' + r + 'clenche', 'Déclenche'),
    ('pr' + r + 'cis', 'précis'),
    ('ap' + r + 's', 'après'),
    ('Ap' + r + 's', 'Après'),
    ('d' + r + 'tail', 'détail'),
    ('D' + r + 'tail', 'Détail'),
    ('d' + r + 'tails', 'détails'),
    ('hiérarchique', 'hiérarchique'),
    ('hi' + r + 'rarchique', 'hiérarchique'),
    ('hi' + r + 'rarchie', 'hiérarchie'),
    ('r' + r + 'side', 'réside'),
    ('n' + r + 'cessaire', 'nécessaire'),
    (r + 'largir', 'élargir'),
    (r + 'larg', 'élarg'),
    (r + 'tape', 'étape'),
    (r + 'tapes', 'étapes'),
    (r + 'galement', 'également'),
    (r + 'gal', 'égal'),
    (r + 'crit', 'écrit'),
    (r + 'cran', 'écran'),
    (r + 'viter', 'éviter'),
    (r + 'vite', 'évite'),
    (r + 'vitement', 'évitement'),
    (r + 'liminer', 'éliminer'),
    (r + 'mis', 'émis'),
    (r + 'mission', 'émission'),
    (r + 'tablir', 'établir'),
    (r + 'tabli', 'établi'),
    (r + 'mettre', 'émettre'),
    (r + 'met', 'émet'),
    ('g' + r + 'n' + r + 'ral', 'général'),
    ('G' + r + 'n' + r + 'ral', 'Général'),
    ('g' + r + 'n' + r + 'r', 'générer'),
    ('G' + r + 'n' + r + 'r', 'Générer'),
    ('g' + r + 'ographique', 'géographique'),
    ('r' + r + 'ponse', 'réponse'),
    ('R' + r + 'ponse', 'Réponse'),
    ('pr' + r + 'sentation', 'présentation'),
    ('pr' + r + 'sente', 'présente'),
    ('pr' + r + 'senter', 'présenter'),
    ('pr' + r + 'sent', 'présent'),
    ('pr' + r + 'v', 'prév'),
    ('pr' + r + 'c', 'préc'),
    ('Pr' + r + 'c', 'Préc'),
    ('diff' + r + 'rence', 'différence'),
    ('diff' + r + 'rent', 'différent'),
    ('g' + r + 'o', 'géo'),
    ('G' + r + 'o', 'Géo'),
    ('s' + r + 'rialis', 'sérialis'),
    ('personnalis' + r, 'personnalisé'),
    ('int' + r + 'gr', 'intégr'),
    ('sp' + r + 'cifi', 'spécifi'),
    ('d' + r + 'fini', 'défini'),
    ('r' + r + 'cup', 'récup'),
    (r + 'v' + r + 'nement', 'événement'),
    ('d' + r + 'tecter', 'détecter'),
    ('d' + r + 'tect', 'détect'),
    ('l' + r + 'ger', 'léger'),
    ('l' + r + 'g' + r + 're', 'légère'),
    ('saisonni' + r + 're', 'saisonnière'),
    ('cat' + r + 'gorie', 'catégorie'),
    ('Cat' + r + 'gorie', 'Catégorie'),
    ('coh' + r + 'rence', 'cohérence'),
    ('coh' + r + 'rent', 'cohérent'),
    ('sch' + r + 'ma', 'schéma'),
    ('derni' + r + 're', 'dernière'),
    ('derni' + r + 'r', 'dernier'),
    ('premi' + r + 're', 'première'),
    ('premi' + r + 'r', 'premier'),
    ('enti' + r + 're', 'entière'),
    ('compl' + r + 'te', 'complète'),
    ('h' + r + 'ritage', 'héritage'),
    ('h' + r + 'rite', 'hérite'),
    ('caract' + r + 're', 'caractère'),
    ('pi' + r + 'ce', 'pièce'),
    ('Pi' + r + 'ce', 'Pièce'),
    (r + 'tage', 'étage'),
    (r + 'tages', 'étages'),
    (r + ' louer', 'à louer'),
    (r + ' vendre', 'à vendre'),
    ('proximit' + r, 'proximité'),
    ('commodit' + r, 'commodité'),
    ('activ' + r + 'e', 'activée'),
    ('activ' + r, 'activé'),
    ('d' + r + 'sactiv' + r + 'e', 'désactivée'),
    ('d' + r + 'sactiv' + r, 'désactivé'),
    ('avanc' + r, 'avancé'),
    ('Avanc' + r, 'Avancé'),
    ('r' + r + 'cent', 'récent'),
    ('R' + r + 'cent', 'Récent'),
    ('r' + r + 'sultat', 'résultat'),
    ('R' + r + 'sultat', 'Résultat'),
    ('r' + r + 'sidence', 'résidence'),
    ('r' + r + 'f' + r + 'rence', 'référence'),
    (r + 'l' + r + 'ments', 'éléments'),
    (r + 'l' + r + 'ment', 'élément'),
    (r + 'l' + r + 've', 'élève'),
    ('r' + r + 'initial', 'réinitial'),
    ('R' + r + 'initial', 'Réinitial'),
    ('s' + r + 'lection', 'sélection'),
    ('S' + r + 'lection', 'Sélection'),
    ('s' + r + 'lectionner', 'sélectionner'),
    ('S' + r + 'lectionner', 'Sélectionner'),
    ('r' + r + 'sidentiel', 'résidentiel'),
    ('id' + r + 'al', 'idéal'),
    ('id' + r + 'alement', 'idéalement'),
    ('entr' + r + 'e', 'entrée'),
    ('Entr' + r + 'e', 'Entrée'),
    ('D' + r + 'marche', 'Démarche'),
    ('d' + r + 'marche', 'démarche'),
    ('f' + r + 't', 'fêt'),
    ('bo' + r + 'te', 'boîte'),
    ('cha' + r + 'ne', 'chaîne'),
    ('ma' + r + 'tre', 'maître'),
    ('fili' + r + 're', 'filière'),
    ('m' + r + 'tier', 'métier'),
    ('M' + r + 'tier', 'Métier'),
    ('cr' + r + 'er', 'créer'),
    ('cr' + r + 'ation', 'création'),
    ('Cr' + r + 'ation', 'Création'),
    ('utilisat' + r, 'utilisat'),
    ('utilis' + r + 'es', 'utilisées'),
    ('utilis' + r + 'e', 'utilisée'),
    ('utilis' + r, 'utilisé'),
    ('surmont' + r, 'surmonté'),
    ('impact' + r, 'impacté'),
    ('POINT-IN-POLYGON ' + r + ' ray', 'POINT-IN-POLYGON – ray'),
    ('POI ICON HELPER ' + r + ' circular', 'POI ICON HELPER – circular'),
    ('SVG paths ' + r + ' partag', 'SVG paths – partag'),
    ('POIs ' + r + ' ' + r + 'coles', 'POIs – Écoles'),
    ('POIs statiques ' + r + ' Facult', 'POIs statiques – Facult'),
    ('Annonces ' + r + ' affich', 'Annonces – affich'),
    (' ' + r + ' on alterne', ' – on alterne'),
    ('de d' + r + 'monter', 'de démonter'),
    ('Ferm' + r + 'e', 'Fermée'),
    ('seuls les localisations v' + r + 'rifi', 'seules les localisations vérifi'),
    ('v' + r + 'rifi', 'vérifi'),
    ('V' + r + 'rifi', 'Vérifi'),
    ('clob' + r + 'rent', 'clobèrent'),
    ('d' + r + 'j' + r, 'déjà'),
    ('d' + r + 'j', 'déj'),
    ('D' + r + 'j', 'Déj'),
    ('cl' + r + 's', 'clés'),
    ('cl' + r, 'clé'),
    ('Cl' + r, 'Clé'),
    (r + 'puis', 'épuis'),
    ('d' + r + 'placer', 'déplacer'),
    ('d' + r + 'plac', 'déplac'),
    ('r' + r + 'cup' + r + 'r', 'récupér'),
    ('r' + r + 'pand', 'répand'),
    ('r' + r + 'p' + r + 't', 'répét'),
    ('r' + r + 'ponde', 'réponde'),
    ('r' + r + 'ponse', 'réponse'),
    ('op' + r + 'ration', 'opération'),
    ('Op' + r + 'ration', 'Opération'),
    ('g' + r + 're', 'gère'),
    ('g' + r + 'rer', 'gérer'),
    ('G' + r + 'rer', 'Gérer'),
    ('mise ' + r + ' jour', 'mise à jour'),
    ('Mise ' + r + ' jour', 'Mise à jour'),
    (' ' + r + ' jour', ' à jour'),
    (' ' + r + ' chaque', ' à chaque'),
    (' ' + r + ' l', ' à l'),
    (' ' + r + ' partir', ' à partir'),
    (' ' + r + ' droite', ' à droite'),
    (' ' + r + ' gauche', ' à gauche'),
    (' ' + r + ' cet', ' à cet'),
    (' ' + r + ' ce ', ' à ce '),
    (' ' + r + ' la ', ' à la '),
    (' ' + r + ' le ', ' à le '),
    (' ' + r + ' les ', ' à les '),
    (' ' + r + ' un ', ' à un '),
    (' ' + r + ' une ', ' à une '),
    (' ' + r + ' son ', ' à son '),
    (' ' + r + ' sa ', ' à sa '),
    (' ' + r + ' ses ', ' à ses '),
    (r + ' la carte', 'à la carte'),
    (r + ' travers', 'à travers'),
    (r + ' cause', 'à cause'),
    (r + ' nouveau', 'à nouveau'),
    (r + ' jour', 'à jour'),
    (r + ' noter', 'à noter'),
]

count = 0
for old, new in fixes:
    if old != new and old in c:
        c = c.replace(old, new)
        count += 1

remaining = c.count('�')
print(f"Applied {count} fixes. Remaining FFFD: {remaining}")

with open(f, 'w', encoding='utf-8') as fh:
    fh.write(c)
print("Saved.")
